url: https://iandefilippi.github.io
baseurl: /imperia2/

# Site settings
title: Imperia Agro
email: iandflp@gmail.com
description: "Hongos frescos como nunca los has probado."


# Team names, titles and social links
people:
- name: Oscar Cacho
  pic: 1
  position: Gerente General
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
    - title: instagram
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
# - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Los Paujiles 111
  - line: Lima, Peru

# Build settings
markdown: kramdown
permalink: pretty
